#dataset parameters
BUCKET_NAME : 'nlpdataset'
ZIP_FILE_NAME  : 'huggingfacedata.zip'


tokenizer_name : 'google/pegasus-cnn_dailymail'
model_name: 'google/pegasus-cnn_dailymail'



#training parameters
num_train_epochs: 1
warmup_steps: 500
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
weight_decay: 0.01
logging_steps: 10
evaluation_strategy: "steps"
eval_steps: 500
save_steps: 1000000  # Equivalent to 1e6
gradient_accumulation_steps: 4